In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import seaborn as sns

In [4]:
import matplotlib.pyplot as plt

In [5]:
train=pd.read_csv('titanic_train.csv')

In [6]:
test=pd.read_csv('titanic_test.csv')

In [7]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Cleaning the training data

In [8]:
train.drop('PassengerId',axis=1,inplace=True)

In [9]:
train.drop('Name',axis=1,inplace=True)

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    object
 7   Fare      891 non-null    float64
 8   Cabin     204 non-null    object
 9   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 69.7+ KB

In [11]:
train.drop('Cabin',axis=1,inplace=True)

In [12]:
train['Age'].fillna(train['Age'].median(),inplace=True)

C:\Users\gupta\AppData\Local\Temp\ipykernel_26588\1796799961.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Age'].fillna(train['Age'].median(),inplace=True)

In [13]:
train['Embarked'].fillna('Unknown',inplace=True)

C:\Users\gupta\AppData\Local\Temp\ipykernel_26588\4048681069.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Embarked'].fillna('Unknown',inplace=True)

In [14]:
train=pd.get_dummies(train,columns=['Sex'],drop_first=True)

In [15]:
train=pd.get_dummies(train,columns=['Embarked'],drop_first=True)

In [16]:
bool_columns=train.select_dtypes(include='bool').columns

In [17]:
train[bool_columns]=train[bool_columns].astype(int)

In [18]:
train.head()

,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare,Sex_male,Embarked_Q,Embarked_S,Embarked_Unknown
0,0,3,22.0,1,0,A/5 21171,7.2500,1,0,1,0
1,1,1,38.0,1,0,PC 17599,71.2833,0,0,0,0
2,1,3,26.0,0,0,STON/O2. 3101282,7.9250,0,0,1,0
3,1,1,35.0,1,0,113803,53.1000,0,0,1,0
4,0,3,35.0,0,0,373450,8.0500,1,0,1,0

In [19]:
train.drop('Embarked_Unknown',axis=1,inplace=True)

In [20]:
train.head()

,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,A/5 21171,7.2500,1,0,1
1,1,1,38.0,1,0,PC 17599,71.2833,0,0,0
2,1,3,26.0,0,0,STON/O2. 3101282,7.9250,0,0,1
3,1,1,35.0,1,0,113803,53.1000,0,0,1
4,0,3,35.0,0,0,373450,8.0500,1,0,1

Cleaning the testing data

In [21]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [22]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [23]:
test.drop('PassengerId',axis=1,inplace=True)

In [24]:
test.drop('Name',axis=1,inplace=True)

In [25]:
test['Age'].fillna(test['Age'].median(),inplace=True)

C:\Users\gupta\AppData\Local\Temp\ipykernel_26588\309680536.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Age'].fillna(test['Age'].median(),inplace=True)

In [26]:
test.drop('Cabin',axis=1,inplace=True)

In [27]:
test=pd.get_dummies(test,columns=['Sex'],drop_first=True)

In [28]:
test=pd.get_dummies(test,columns=['Embarked'],drop_first=True)

In [29]:
test.head()

,Pclass,Age,SibSp,Parch,Ticket,Fare,Sex_male,Embarked_Q,Embarked_S
0,3,34.5,0,0,330911,7.8292,True,True,False
1,3,47.0,1,0,363272,7.0000,False,False,True
2,2,62.0,0,0,240276,9.6875,True,True,False
3,3,27.0,0,0,315154,8.6625,True,False,True
4,3,22.0,1,1,3101298,12.2875,False,False,True

In [30]:
bool_cols1=test.select_dtypes(include='bool').columns

In [31]:
test[bool_cols1]=test[bool_cols1].astype(int)

In [35]:
test.head()

,Pclass,Age,SibSp,Parch,Ticket,Fare,Sex_male,Embarked_Q,Embarked_S
0,3,34.5,0,0,330911,7.8292,1,1,0
1,3,47.0,1,0,363272,7.0000,0,0,1
2,2,62.0,0,0,240276,9.6875,1,1,0
3,3,27.0,0,0,315154,8.6625,1,0,1
4,3,22.0,1,1,3101298,12.2875,0,0,1

In [37]:
test.drop('Ticket',axis=1,inplace=True)

In [38]:
train.drop('Ticket',axis=1,inplace=True)

In [39]:
train.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0
2,1,3,26.0,0,0,7.9250,0,0,1
3,1,1,35.0,1,0,53.1000,0,0,1
4,0,3,35.0,0,0,8.0500,1,0,1

In [40]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Sex_male    891 non-null    int64
 7   Embarked_Q  891 non-null    int64
 8   Embarked_S  891 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 62.8 KB

In [42]:
test['Fare'].fillna(test['Fare'].median(),inplace=True)

C:\Users\gupta\AppData\Local\Temp\ipykernel_26588\792478972.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Fare'].fillna(test['Fare'].median(),inplace=True)

In [43]:
test.head()

   Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0       3  34.5      0      0   7.8292         1           1           0
1       3  47.0      1      0   7.0000         0           0           1
2       2  62.0      0      0   9.6875         1           1           0
3       3  27.0      0      0   8.6625         1           0           1
4       3  22.0      1      1  12.2875         0           0           1

In [44]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      418 non-null    int64
 1   Age         418 non-null    float64
 2   SibSp       418 non-null    int64
 3   Parch       418 non-null    int64
 4   Fare        418 non-null    float64
 5   Sex_male    418 non-null    int64
 6   Embarked_Q  418 non-null    int64
 7   Embarked_S  418 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 26.3 KB

Now, we have both train and test datsets clean, and without null values

In [46]:
train.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [47]:
#trained on the train data
X_train=train[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male','Embarked_Q', 'Embarked_S']]

In [48]:
y_train=train['Survived']

In [49]:
from sklearn.linear_model import LogisticRegression

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
lm=LogisticRegression(max_iter=1000)

In [52]:
lm.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [53]:
#testing on the test data
y_pred=lm.predict(test)

In [54]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [56]:
status = pd.Series(y_pred).map({1:'Survived', 0:'Not Survived'})

In [58]:
test["Survival Status"]=status

In [59]:
test.head()

,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S,Survival Status
0,3,34.5,0,0,7.8292,1,1,0,Not Survived
1,3,47.0,1,0,7.0000,0,0,1,Not Survived
2,2,62.0,0,0,9.6875,1,1,0,Not Survived
3,3,27.0,0,0,8.6625,1,0,1,Not Survived
4,3,22.0,1,1,12.2875,0,0,1,Survived

since, in test data, we dont have survived column outcomes alr, so we cant compare, and neither we can get classification report
cause we dont have actual or true values of Survived column